name: release

on:
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure Java
        uses: actions/setup-java@v1
        with:
          java-version: 8
          server-id: ossrh-releases
          server-username: OSSRH_USER
          server-password: OSSRH_PASS
          gpg-private-key: ${{ secrets.GPG_SIGNING_KEY }}
          gpg-passphrase: GPG_PASSPHRASE
      - name: Configure Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 'jruby-9.1.17.0'
      - name: Download Java dependencies
        run: |
          mvn dependency:resolve -Psonatype-oss-release
          mvn dependency:resolve-plugins -Psonatype-oss-release
      - name: Download Ruby dependencies
        run: |
          gem install bundler --version 1.15.3
          bundle _1.15.3_ install
      - name: Release war
        #if: contains(github.ref, 'refs/tags/v')
        env:
          OSSRH_USER: ${{ secrets.OSSRH_USER }}
          OSSRH_PASS: ${{ secrets.OSSRH_PASS }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          mvn release:perform
